// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace InterViewer.iOS
{
	public partial class FileManagerTableCell : UITableViewCell
	{
		public FileManagerTableCell (IntPtr handle) : base (handle)
		{
		}
		public void ReloadData(string filePath, bool fileOrFolder)
		{
			LabelFilePath.Text = filePath;
			if (fileOrFolder == true)
				ButtonSelected.SetTitle("File",UIControlState.Normal);
			else
				ButtonSelected.SetTitle("Path", UIControlState.Normal);
		}
	}
}
