// This file has been autogenerated from a class added in the UI designer.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UIKit;

namespace InterViewer.iOS
{
	public partial class ImageManagerController : UIViewController
	{
		ImageManagerTableSource source;
		List<FileListAttributes> listFilePathName;
		string pathRightNow;
		public ImageManagerController (IntPtr handle) : base (handle)
		{
		}
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			//Manager Start
			listFilePathName = getFileAndPathList("/");
			pathRightNow = "/";
			//警告,FileManagerTableSource,可能造成記憶體問題
			source = new ImageManagerTableSource(listFilePathName);
			ImageManagerTableView.Source = source;
			source.ItemClick += ListButton_Click;
			ImageManagerTableView.ReloadData();

			ReturnButton.TouchUpInside += ReturnButton_Click;
		}
		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			// Release any cached data, images, etc that aren't in use.
		}
		private void ReturnButton_Click(object sender, EventArgs e)
		{
			char[] seperater = { '/' };
			string[] pathTemp = pathRightNow.Split(seperater);
			string pathForQuery = string.Empty;
			if (pathTemp.Length > 2)
			{
				for (int i = 1; i < pathTemp.Length - 1; i++)
				{
					pathForQuery += "/";
					pathForQuery += pathTemp[i];
				}
			}
			else
			{
				pathForQuery += "/";
			}
			listFilePathName = getFileAndPathList(pathForQuery);
			source = new ImageManagerTableSource(listFilePathName);
			ImageManagerTableView.Source = source;
			source.ItemClick += ListButton_Click;
			ImageManagerTableView.ReloadData();
			ReturnButton.SetTitle("<< " + pathForQuery, UIControlState.Normal);
			pathRightNow = pathForQuery;
		}
		private void ListButton_Click(object sender, ImageManagerTableSource.SelectedEventArgs e)
		{
			bool isFilePNG = isPNG(e.SelectedName.Name);
			string _folderSlides = Environment.GetFolderPath(Environment.SpecialFolder.Personal) + @"/InterView/Sliders";
			if (e.SelectedName.IsFile == true)
			{
				if (isFilePNG == true)
				{
					if (!File.Exists(_folderSlides))
						Directory.CreateDirectory(_folderSlides);
					//PNG copy to destination
					File.Copy(e.SelectedName.Name, _folderSlides + "/" + getFileNameFromFullFilePath(e.SelectedName.Name));
					showAlert("新增影像", e.SelectedName.Name + @" 新增成功!!", @"確定", this);
				}
				else
				{
					showAlert("新增影像", e.SelectedName.Name + @" 不是PNG檔案", @"確定", this);
				}
			}
			else
			{
				listFilePathName = getFileAndPathList(e.SelectedName.Name);
				source = new ImageManagerTableSource(listFilePathName);
				ImageManagerTableView.Source = source;
				source.ItemClick += ListButton_Click;
				ImageManagerTableView.ReloadData();
				ReturnButton.SetTitle("<< " + e.SelectedName.Name, UIControlState.Normal);
				pathRightNow = e.SelectedName.Name;
			}
		}
		private List<FileListAttributes> getFileAndPathList(string path)
		{
			List<FileListAttributes> theList = new List<FileListAttributes>();
			FileListAttributes theFileAttributes;
			string[] fileList = getFileList(path);
			string[] pathList = getPathList(path);
			for (int i = 0; i < fileList.Length; i++)
			{
				theFileAttributes = new FileListAttributes(true, fileList[i]);
				theList.Add(theFileAttributes);
			}
			for (int i = 0; i < pathList.Length; i++)
			{
				theFileAttributes = new FileListAttributes(false, pathList[i]);
				theList.Add(theFileAttributes);
			}
			return theList;
		}
		private string[] getFileList(string path)
		{
			try
			{
				var files = Directory.EnumerateFiles(path);
				return files.ToArray<String>();
			}
			catch (System.UnauthorizedAccessException)
			{
				showAlert("Permission denied", "無權進入此檔案夾", "確認", this);
				var files = Directory.EnumerateFiles("/");
				return files.ToArray<String>();
			}
		}
		private string[] getPathList(string path)
		{
			try
			{
				var paths = Directory.EnumerateDirectories(path);
				return paths.ToArray<String>();
			}
			catch (System.UnauthorizedAccessException)
			{
				showAlert("Permission denied", "無權進入此檔案夾", "確認", this);
				var paths = Directory.EnumerateDirectories("/");
				return paths.ToArray<String>();
			}
		}
		private bool isPDF(string fullFilePath)
		{
			//return (getFileNameFromFullFilePath(fullFilePath).Split(new char[] { '.' })[getFileNameFromFullFilePath(fullFilePath).Split(new char[] { '.' }).Length - 1]=="pdf"||getFileNameFromFullFilePath(fullFilePath).Split(new char[] { '.' })[getFileNameFromFullFilePath(fullFilePath).Split(new char[] { '.' }).Length - 1] == "PDF" || getFileNameFromFullFilePath(fullFilePath).Split(new char[] { '.' })[getFileNameFromFullFilePath(fullFilePath).Split(new char[] { '.' }).Length - 1] == "Pdf")? true : false;
			return (Path.GetExtension(fullFilePath) == ".pdf" || Path.GetExtension(fullFilePath) == ".PDF" || Path.GetExtension(fullFilePath) == ".Pdf") ? true : false;
		}
		private bool isPNG(string fullFilePath)
		{
			return (Path.GetExtension(fullFilePath) == ".png" || Path.GetExtension(fullFilePath) == ".PNG" || Path.GetExtension(fullFilePath) == ".Png") ? true : false;
		}
		private string getFileNameFromFullFilePath(string fullFilePath)
		{
			return fullFilePath.Split(new char[] { '/' })[fullFilePath.Split(new char[] { '/' }).Length - 1];
		}
		private string getPathNameFromFullFilePath(string fullFilePath)
		{
			string[] pathTemp = fullFilePath.Split(new char[] { '/' });
			string folderPath = "";
			if (pathTemp.Length > 2)
			{
				for (int i = 1; i < pathTemp.Length - 2; i++)
				{
					folderPath += "/";
					folderPath += pathTemp[i];
				}
			}
			else
			{
				folderPath += "/";
			}

			return folderPath;
		}
		private void showAlert(string title, string message, string actionTitle, UIViewController caller)
		{
			UIAlertController alertController = UIAlertController.Create(title, message, UIAlertControllerStyle.Alert);
			alertController.AddAction(UIAlertAction.Create(actionTitle, UIAlertActionStyle.Default, null));
			caller.PresentViewController(alertController, true, null);
		}
	}
}
