#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("InterViewer.Droid.Test.Resource", IsApplication=true)]

namespace InterViewer.Droid.Test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::InterViewer.Droid.Test.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::InterViewer.Droid.Test.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::InterViewer.Droid.Test.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::InterViewer.Droid.Test.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::InterViewer.Droid.Test.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::InterViewer.Droid.Test.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::InterViewer.Droid.Test.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::InterViewer.Droid.Test.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::InterViewer.Droid.Test.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::InterViewer.Droid.Test.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::InterViewer.Droid.Test.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::InterViewer.Droid.Test.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::InterViewer.Droid.Test.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::InterViewer.Droid.Test.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::InterViewer.Droid.Test.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::InterViewer.Droid.Test.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::InterViewer.Droid.Test.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::InterViewer.Droid.Test.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::InterViewer.Droid.Test.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::InterViewer.Droid.Test.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::InterViewer.Droid.Test.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::InterViewer.Droid.Test.Resource.Layout.test_suite;
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int info = 2131034112;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public const int busy_indicator = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button_normal = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int button_pressed = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int canvas = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int page_indicator = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int seek_progress = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int seek_thumb = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int text_border_focused = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int text_border_normal = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int text_border_pressed = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int text_normal = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int text_pressed = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int toolbar = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int busy = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int darkdenim3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_annot = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_annotation = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_arrow_left = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_arrow_right = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_arrow_up = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_cancel = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_check = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_clipboard = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_dir = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_doc = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_highlight = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_link = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_list = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_magnifying_glass = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_more = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_pen = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_print = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_reflow = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_select = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_share = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_strike = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_trash = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_underline = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_updir = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int page_num = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int search = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int seek_progress = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int seek_thumb = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tiled_background = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090025
			public const int OptionHostName = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int OptionPort = 2131296294;
			
			// aapt resource value: 0x7f090024
			public const int OptionRemoteServer = 2131296292;
			
			// aapt resource value: 0x7f090039
			public const int OptionsButton = 2131296313;
			
			// aapt resource value: 0x7f090034
			public const int ResultFullName = 2131296308;
			
			// aapt resource value: 0x7f090036
			public const int ResultMessage = 2131296310;
			
			// aapt resource value: 0x7f090035
			public const int ResultResultState = 2131296309;
			
			// aapt resource value: 0x7f090033
			public const int ResultRunSingleMethodTest = 2131296307;
			
			// aapt resource value: 0x7f090037
			public const int ResultStackTrace = 2131296311;
			
			// aapt resource value: 0x7f09002f
			public const int ResultsFailed = 2131296303;
			
			// aapt resource value: 0x7f09002c
			public const int ResultsId = 2131296300;
			
			// aapt resource value: 0x7f090030
			public const int ResultsIgnored = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int ResultsInconclusive = 2131296305;
			
			// aapt resource value: 0x7f090032
			public const int ResultsMessage = 2131296306;
			
			// aapt resource value: 0x7f09002e
			public const int ResultsPassed = 2131296302;
			
			// aapt resource value: 0x7f09002d
			public const int ResultsResult = 2131296301;
			
			// aapt resource value: 0x7f090038
			public const int RunTestsButton = 2131296312;
			
			// aapt resource value: 0x7f09003a
			public const int TestSuiteListView = 2131296314;
			
			// aapt resource value: 0x7f09001f
			public const int acceptButton = 2131296287;
			
			// aapt resource value: 0x7f09001e
			public const int annotType = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int cancelAcceptButton = 2131296285;
			
			// aapt resource value: 0x7f09000e
			public const int cancelAnnotButton = 2131296270;
			
			// aapt resource value: 0x7f090014
			public const int cancelDeleteButton = 2131296276;
			
			// aapt resource value: 0x7f090018
			public const int cancelMoreButton = 2131296280;
			
			// aapt resource value: 0x7f090009
			public const int cancelSearch = 2131296265;
			
			// aapt resource value: 0x7f09001a
			public const int copyTextButton = 2131296282;
			
			// aapt resource value: 0x7f090016
			public const int deleteButton = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int deleteLabel = 2131296277;
			
			// aapt resource value: 0x7f090002
			public const int docNameText = 2131296258;
			
			// aapt resource value: 0x7f09001b
			public const int editAnnotButton = 2131296283;
			
			// aapt resource value: 0x7f09000f
			public const int highlightButton = 2131296271;
			
			// aapt resource value: 0x7f090029
			public const int icon = 2131296297;
			
			// aapt resource value: 0x7f090023
			public const int info = 2131296291;
			
			// aapt resource value: 0x7f090012
			public const int inkButton = 2131296274;
			
			// aapt resource value: 0x7f090003
			public const int linkButton = 2131296259;
			
			// aapt resource value: 0x7f090020
			public const int lowerButtons = 2131296288;
			
			// aapt resource value: 0x7f090007
			public const int moreButton = 2131296263;
			
			// aapt resource value: 0x7f09002a
			public const int name = 2131296298;
			
			// aapt resource value: 0x7f090005
			public const int outlineButton = 2131296261;
			
			// aapt resource value: 0x7f090028
			public const int page = 2131296296;
			
			// aapt resource value: 0x7f090022
			public const int pageNumber = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int pageSlider = 2131296289;
			
			// aapt resource value: 0x7f090019
			public const int printButton = 2131296281;
			
			// aapt resource value: 0x7f090004
			public const int reflowButton = 2131296260;
			
			// aapt resource value: 0x7f09000b
			public const int searchBack = 2131296267;
			
			// aapt resource value: 0x7f090006
			public const int searchButton = 2131296262;
			
			// aapt resource value: 0x7f09000c
			public const int searchForward = 2131296268;
			
			// aapt resource value: 0x7f09000a
			public const int searchText = 2131296266;
			
			// aapt resource value: 0x7f090011
			public const int strikeOutButton = 2131296273;
			
			// aapt resource value: 0x7f090000
			public const int switcher = 2131296256;
			
			// aapt resource value: 0x7f090027
			public const int title = 2131296295;
			
			// aapt resource value: 0x7f090001
			public const int topBar0Main = 2131296257;
			
			// aapt resource value: 0x7f090008
			public const int topBar1Search = 2131296264;
			
			// aapt resource value: 0x7f09000d
			public const int topBar2Annot = 2131296269;
			
			// aapt resource value: 0x7f090013
			public const int topBar3Delete = 2131296275;
			
			// aapt resource value: 0x7f090017
			public const int topBar4More = 2131296279;
			
			// aapt resource value: 0x7f09001c
			public const int topBar5Accept = 2131296284;
			
			// aapt resource value: 0x7f090010
			public const int underlineButton = 2131296272;
			
			// aapt resource value: 0x7f09002b
			public const int webview = 2131296299;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int buttons = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int options = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int outline_entry = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int picker_entry = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int print_dialog = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int results = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int test_result = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int test_suite = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int textentry = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070031
			public const int accept = 2131165233;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int cancel = 2131165188;
			
			// aapt resource value: 0x7f07002a
			public const int cannot_open_buffer = 2131165226;
			
			// aapt resource value: 0x7f070027
			public const int cannot_open_document = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int cannot_open_document_Reason = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int cannot_open_file_Path = 2131165225;
			
			// aapt resource value: 0x7f07002d
			public const int choose_value = 2131165229;
			
			// aapt resource value: 0x7f070022
			public const int copied_to_clipboard = 2131165218;
			
			// aapt resource value: 0x7f070011
			public const int copy = 2131165201;
			
			// aapt resource value: 0x7f070032
			public const int copy_text = 2131165234;
			
			// aapt resource value: 0x7f07002f
			public const int copy_text_to_the_clipboard = 2131165231;
			
			// aapt resource value: 0x7f070013
			public const int delete = 2131165203;
			
			// aapt resource value: 0x7f07001a
			public const int dismiss = 2131165210;
			
			// aapt resource value: 0x7f070026
			public const int document_has_changes_save_them_ = 2131165222;
			
			// aapt resource value: 0x7f070024
			public const int draw_annotation = 2131165220;
			
			// aapt resource value: 0x7f070016
			public const int edit_annotations = 2131165206;
			
			// aapt resource value: 0x7f07000a
			public const int enter_password = 2131165194;
			
			// aapt resource value: 0x7f07001e
			public const int entering_reflow_mode = 2131165214;
			
			// aapt resource value: 0x7f07002b
			public const int fill_out_text_field = 2131165227;
			
			// aapt resource value: 0x7f070033
			public const int format_currently_not_supported = 2131165235;
			
			// aapt resource value: 0x7f070014
			public const int highlight = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int ink = 2131165207;
			
			// aapt resource value: 0x7f07001f
			public const int leaving_reflow_mode = 2131165215;
			
			// aapt resource value: 0x7f070030
			public const int more = 2131165232;
			
			// aapt resource value: 0x7f07001d
			public const int no = 2131165213;
			
			// aapt resource value: 0x7f07000e
			public const int no_further_occurrences_found = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int no_media_hint = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int no_media_warning = 2131165186;
			
			// aapt resource value: 0x7f070023
			public const int no_text_selected = 2131165219;
			
			// aapt resource value: 0x7f07002e
			public const int not_supported = 2131165230;
			
			// aapt resource value: 0x7f070025
			public const int nothing_to_save = 2131165221;
			
			// aapt resource value: 0x7f07002c
			public const int okay = 2131165228;
			
			// aapt resource value: 0x7f070009
			public const int outline_title = 2131165193;
			
			// aapt resource value: 0x7f07001b
			public const int parent_directory = 2131165211;
			
			// aapt resource value: 0x7f070008
			public const int picker_title_App_Ver_Dir = 2131165192;
			
			// aapt resource value: 0x7f070019
			public const int print = 2131165209;
			
			// aapt resource value: 0x7f070020
			public const int print_failed = 2131165216;
			
			// aapt resource value: 0x7f070018
			public const int save = 2131165208;
			
			// aapt resource value: 0x7f070010
			public const int search = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int search_backwards = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int search_document = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int search_forwards = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int searching_ = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int select = 2131165199;
			
			// aapt resource value: 0x7f070021
			public const int select_text = 2131165217;
			
			// aapt resource value: 0x7f070012
			public const int strike_out = 2131165202;
			
			// aapt resource value: 0x7f07000b
			public const int text_not_found = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int toggle_links = 2131165197;
			
			// aapt resource value: 0x7f070034
			public const int toggle_reflow_mode = 2131165236;
			
			// aapt resource value: 0x7f070015
			public const int underline = 2131165205;
			
			// aapt resource value: 0x7f070001
			public const int version = 2131165185;
			
			// aapt resource value: 0x7f07001c
			public const int yes = 2131165212;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppBaseTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
